"""Readable measured results, generated from the released raw logs."""
from pathlib import Path
import json,numpy as np
ROOT=Path(__file__).resolve().parent

def run():
    c=json.loads((ROOT/'data/whole_body_cmg.json').read_text());v=json.loads((ROOT/'results/full_validation.json').read_text());i=json.loads((ROOT/'results/instantaneous.json').read_text());m=json.loads((ROOT/'results/motion_summary.json').read_text());f=json.loads((ROOT/'results/floating_motion_summary.json').read_text());fine=m['runs'][-1];stand=f['standing'][-1];coast=f['coast'][-1]
    a=np.load(ROOT/'results/motion_dt_5e-05.npz');t=a['time'];h=a['history'];power=h[:,9:21]*h[:,21:33];work=np.trapezoid(power,t,axis=0);positive=np.trapezoid(np.maximum(power,0),t,axis=0);negative=np.trapezoid(np.minimum(power,0),t,axis=0)
    perport=[dict(actuator=port['id'],joint=port['joint'],peak_force_N=float(np.max(abs(h[:,9+k]))),peak_mechanical_power_W=float(np.max(abs(power[:,k]))),signed_mechanical_work_J=float(work[k]),positive_mechanical_work_J=float(positive[k]),negative_mechanical_work_J=float(negative[k])) for k,port in enumerate(c['actuators'])]
    (ROOT/'results/actuator_energy.json').write_text(json.dumps(perport,indent=2)+'\n')
    lines=['# Measured results — full-body Kangaroo v20','',f"**{v['status']} — {v['gates_passed']}/{v['gates_total']} required numerical gates passed.**",'', 'This verdict applies to the explicit published-cut reconstruction recorded in the CMG metadata; the altered joint topology has not been validated against hardware.','',f"Runtime: {v['elapsed_seconds']:.1f} seconds. Environment: {v['environment']}.",'','## Coverage','',f"The 42.214867608 kg prototype contains 78 physical bodies, 76 internal scalar coordinates, a floating pelvis and 12 physical force actuators. Exact kinematics cover 37 configurations, 3 gravity vectors and 222 floating force cases. Supported inverse dynamics additionally covers 111 cases. Both legs move simultaneously in the four-second native experiment.",'','## Independent calculations','', '| Quantity | Maximum absolute difference/residual |','|---|---:|']
    for name,label in [('se3_residual','PACDM all-row SE(3) residual'),('mass_pin','Mass matrix: NumPy vs Pinocchio'),('mass_mj','Mass matrix: NumPy vs MuJoCo'),('bias_pin','Bias: NumPy vs Pinocchio'),('bias_mj','Bias: NumPy vs MuJoCo'),('kkt_acceleration','Reduced vs KKT acceleration'),('energy_rate','Independent energy-rate identity (W)'),('reaction_power','Exact loop reaction power (W)')]:lines.append(f"| {label} | {i['maxima'][name]:.6g} |")
    lines+=['','These componentwise tolerances mix the relevant SI dimensions for matrix/vector entries; they are numerical agreement checks, not hardware accuracy estimates. All detailed limits are preserved in JSON.','','## All-actuator native motion','','| Timestep (microseconds) | Motor tracking RMS (micrometres) | Point gap (micrometres) | Universal dot residual | Energy ledger maximum (mJ) |','|---:|---:|---:|---:|---:|']
    for r in m['runs']:lines.append(f"| {r['timestep_s']*1e6:g} | {r['tracking_rms_m']*1e6:.6f} | {r['maximum_point_gap_m']*1e6:.6f} | {r['maximum_universal_dot']:.6g} | {r['energy_ledger_max_error_J']*1e3:.6f} |")
    lines+=['',f"At 50 microseconds, maximum actual motor force is {fine['maximum_motor_force_N']:.3f} N against the source ±5000 N bounds. No saturation, source joint-limit violation, MuJoCo warning or externally applied generalized force occurs. Minimum prismatic margin is {fine['minimum_prismatic_margin_m']*1000:.3f} mm; minimum revolute margin is {fine['minimum_revolute_margin_rad']:.6f} rad.",'',f"Same-gain PD without feedforward gives {m['pd_control']['tracking_rms_m']*1000:.6f} mm RMS motor error. This is an ablation, not an optimized-controller comparison. Disabling loop constraints produces {m['negative_control']['maximum_point_gap_m']*1000:.3f} mm point separation in 0.3 s.",'','## Mechanical energy at 50 microseconds','','| Term over the four-second run | Energy (J) |','|---|---:|']
    for key,label in [('motor_work_J','Actual motor work'),('damping_work_J','Viscous dissipation, signed'),('constraint_work_J','Native compliant loop work'),('energy_change_J','Change in kinetic + potential + armature energy'),('energy_ledger_final_error_J','Final energy ledger residual')]:lines.append(f"| {label} | {fine[key]:.9f} |")
    lines+=['','The large positive motor work is mostly dissipated by the source joint damping. Native equality constraints have a small measured work contribution. Electrical energy, battery use and regenerative efficiency are not modeled.','','## Per-actuator force, power and work','','| Actuator joint | Peak force magnitude (N) | Peak power magnitude (W) | Signed mechanical work (J) |','|---|---:|---:|---:|']
    for row in perport:lines.append(f"| `{row['joint']}` | {row['peak_force_N']:.4f} | {row['peak_mechanical_power_W']:.4f} | {row['signed_mechanical_work_J']:.6f} |")
    lines+=['','Positive and negative work are also available per actuator in `results/actuator_energy.json`. Negative mechanical work does not establish electrical regeneration.','','## Floating-base standing','',f"At 25 microseconds, mean final vertical ground force is **{stand['mean_final_ground_force_N'][2]:.6f} N**, compared with **{stand['weight_N']:.6f} N** robot weight. The floor supports the real floating pelvis; no pelvis actuator or externally applied generalized force is used.",'',f"The two-second run reaches a maximum actual motor force of {stand['maximum_motor_force_N']:.3f} N. Maximum motor coordinate error is {stand['maximum_motor_position_error_m']*1000:.4f} mm. Maximum pelvis displacement is {stand['maximum_root_translation_m']*1000:.3f} mm and final-window speed is at most {stand['maximum_final_root_speed_m_s']*1000:.3f} mm/s. This is a settling standing test, not perfect static fixation or demonstrated locomotion.",'',f"Maximum point gap is {stand['maximum_point_gap_m']*1e6:.6f} micrometres; universal dot error is {stand['maximum_universal_dot']:.6g}; energy ledger error is {stand['maximum_energy_ledger_error_J']*1000:.6f} mJ. All physical position/force limits pass and there are no native warnings.",'','## Free-body conservation','',f"The 0.4-second, undriven, undamped, zero-gravity coast starts with {coast['initial_kinetic_energy_J']:.9f} J kinetic energy. At 100 microseconds, maximum energy drift is {coast['maximum_energy_drift_J']:.6g} J and the largest linear/angular momentum component difference is {coast['maximum_momentum_error_mixed_SI']:.6g} in the corresponding SI unit. Both decrease on timestep refinement.",'','## Interpretation and next use','','These tests demonstrate the framework operating on a complete, explicitly defined multi-loop robot with physical actuator coordinates and independently checked mechanics. All results remain conditional on the documented loop-joint reconstruction. Author-verified attachment frames, broader trajectories, contact-rich locomotion and Isaac Sim execution remain separate validation targets.']
    (ROOT/'RESULTS.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':run()
